ezsystems/ezplatform-rest

- composer.json
I really like the solution provided by @mnocon which combines Composer's `"minimum-stability": "dev"` and `"prefer-stable": true` settings. 
This way we can avoid explicitly setting `@dev` versions of dependencies of dependencies when there's no stable version yet.
At the same time we want to avoid installing 3rd party unstable packages, hence `prefer-stable` is set to true.
This PR:
> [Composer] Set minimum-stability and prefer-stable

- src/lib/Output/Generator.php
- tests/lib/Output/Generator/JsonTest.php
- tests/lib/Output/Generator/XmlTest.php
- tests/lib/Output/Generator/_fixtures/testGeneratorStartEndAttribute.xml
- tests/lib/Output/Generator/_fixtures/testGeneratorStartEndValueElement.xml
> JIRA: https://jira.ez.no/browse/EZP-30685
This PR introduces two shortcut methods to simplify `\EzSystems\EzPlatformRest\Output\ValueObjectVisitor` implementation: 
* `\EzSystems\EzPlatformRest\Output\Generator::valueElement` which is equivalent to  
```php
$generator->startValueElement($name, $value);
$generator->endValueElement($name);
```
* `\EzSystems\EzPlatformRest\Output\Generator::attribute` which is equivalent to  
```php
$generator->startAttribute($name, $value);
$generator->endAttribute($name);
```
> EZP-30685: As a Developer I want to easier generate attribute/value elements in Value Object Visitors

- tests/bundle/Functional/TestCase.php
This PR provides a possibility to set HTTP scheme of the eZ Platform instance for REST tests.
HTTP scheme (http or https) can be set via the new environment variable `EZP_TEST_REST_SCHEME` which falls back to `http` as default.
_Background: Symfony CLI allows to run local HTTP server with `HTTPS`, so it's quite possible more people would need it in the future._
> [Tests] Allowed configuring HTTP scheme for REST tests instance

- src/lib/Server/Security/RestAuthenticator.php
- tests/lib/Server/Security/RestSessionBasedAuthenticatorTest.php
> JIRA: https://jira.ez.no/browse/EZP-30812
Fixed the following deprecation message:
```
Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.
```
by swapping argument order in  `Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()` method calls.
> EZP-30812: Fixed deprecated use of Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch method

- tests/bundle/Functional/SessionTest.php
The equivalent of https://github.com/ezsystems/ezpublish-kernel/pull/2693 v7.5 in master - the test file has moved.
⚠ SessionTest will fail here, but passes if https://github.com/ezsystems/ezplatform/pull/435 is merged in master.
> EZP-30515: Enable CSRF token in login form by default

- src/bundle/Resources/config/services.yml
- src/lib/Server/Controller/SessionController.php
- src/lib/Server/Controller/User.php
>Jira: https://jira.ez.no/browse/EZP-30934
> EZP-30934: Removed usage of deprecated getCurrentUser method

- src/lib/Server/Controller/Role.php
- tests/bundle/Functional/RoleTest.php
| **JIRA issue**     | [EZP-30971](https://jira.ez.no/browse/EZP-30971)
| **Type**           | Improvement
| **Target version** | `master`
| **BC breaks**      | yes
As additional thing, some methods were cleared up to use only `roleDraftId` and not `try/catch` to guess if you passed `roleDraftId` or `roleId`.
> EZP-30971: Removed usage of deprecated role service methods

- src/lib/Server/Output/ValueObjectVisitor/RestContent.php
- tests/lib/Server/Output/ValueObjectVisitor/RestContentTest.php
| **JIRA issue**     | [EZP-31115](https://jira.ez.no/browse/EZP-31115)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `master`
Added `isHidden` flag to `ContentInfo` in REST response
**TODO**:
> EZP-31115: Added `isHidden` flag to `ContentInfo` in REST response

- src/lib/Server/Output/ValueObjectVisitor/RestLocation.php
- tests/lib/Server/Output/ValueObjectVisitor/RestLocationRootNodeTest.php
- tests/lib/Server/Output/ValueObjectVisitor/RestLocationTest.php
| **JIRA issue**     | [EZP-31122](https://jira.ez.no/browse/EZP-31122)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `master`
Added `explicitlyHidden` flag to `Location` in REST response
**TODO**:
> EZP-31122: Added explicitlyHidden flag to Location in REST response

- composer.json
| Question | Answer
| ------------ | ------------------
| **Type**  | bug
The package codebase uses the following PHP extensions:
* ext-dom,
* ext-json,
* ext-libxml,
* ext-simplexml,
* ext-xmlwriter.
They need to be present in `composer.json` so an issue is reported when performing composer install. It's also a DX improvement when working with this package (PhpStorm reports missing extensions which is distracting).
**TODO**:
> [Composer] Added missing requirements for PHP extensions

- composer.json
Making sure correct dependencies are installed when installing this package locally, to unblock: https://github.com/ezsystems/ezplatform-rest/pull/33
Right now, because of minimum-stabiltiy and prefer stable settings, the Kernel package is installed in beta version. This PR changes that.
> Install latest dependencies

- tests/bundle/Functional/xsd/Version.xsd
| **JIRA issue**     | -
Updated `Thumbnail` element schema in `tests/bundle/Functional/xsd/Version.xsd` in order to fix broken CI build: https://travis-ci.org/ezsystems/ezplatform-rest/builds/633492050
**TODO**:
> Updated Thumbnail element schema in tests/bundle/Functional/xsd/Version.xsd

- src/lib/Server/Output/ValueObjectVisitor/ContentList.php
- src/lib/Server/Values/ContentList.php
- tests/lib/Server/Output/ValueObjectVisitor/ContentListTest.php
| **JIRA issue**     | Used in [EZP-31316](https://jira.ez.no/browse/EZP-31316) for https://github.com/ezsystems/ezplatform-query-fieldtype/pull/20
| **Bug/Improvement**| improvement
| **New feature**    | yes
| **Target version** | `1.x`
| **BC breaks**      | yes (extra required argument for `ContentList`)
| **Doc needed**     | yes (but not really, since that value object isn't exposed in the REST API)
Merged from https://github.com/ezsystems/ezpublish-kernel/pull/2936.
Adds a `totalCount` attribute to the REST response for `ContentList`. Used for pagination.
Note: since this value object is not used in the core REST API, it requires the query field type pull-request above to test it (or …
> Added totalCount attribute to REST ContentList response

- src/bundle/Resources/config/input_parsers.yml
- src/lib/Server/Input/Parser/Criterion/IsUserBased.php
- src/lib/Server/Input/Parser/Criterion/IsUserEnabled.php
- src/lib/Server/Input/Parser/Criterion/ObjectStateIdentifier.php
- src/lib/Server/Input/Parser/Criterion/SectionIdentifier.php
- src/lib/Server/Input/Parser/Criterion/UserEmail.php
- src/lib/Server/Input/Parser/Criterion/UserId.php
- src/lib/Server/Input/Parser/Criterion/UserLogin.php
- tests/bundle/Functional/SearchView/Criterion/IsUserBasedTest.php
- tests/bundle/Functional/SearchView/Criterion/IsUserEnabledTest.php
- tests/bundle/Functional/SearchView/Criterion/ObjectStateIdentifierTest.php
- tests/bundle/Functional/SearchView/Criterion/SectionIdentifierTest.php
- tests/bundle/Functional/SearchView/Criterion/UserEmailTest.php
- tests/bundle/Functional/SearchView/Criterion/UserIdTest.php
- tests/bundle/Functional/SearchView/Criterion/UserLoginTest.php
- tests/bundle/Functional/SearchView/SearchCriterionTestCase.php
- tests/bundle/Functional/SearchView/SearchViewTest.php
- tests/bundle/Functional/SearchView/SearchViewTestCase.php
| **JIRA issue**     | [EZP-31080](https://jira.ez.no/browse/EZP-31080)
| **Type**| feature
This PR adds REST input parsers for https://github.com/ezsystems/ezpublish-kernel/pull/2952
Passing build: https://travis-ci.org/github/ezsystems/ezplatform-rest/builds/661032225?utm_source=github_status&utm_medium=notification
**TODO**:
> EZP-31080: Created missing search Criterions

- src/bundle/Resources/config/input_parsers.yml
- src/lib/Server/Input/Parser/Criterion/Sibling.php
- tests/lib/Server/Input/Parser/Criterion/SiblingTest.php
| **JIRA issue**     | [EZP-31415](https://jira.ez.no/browse/EZP-31415)
| **Requires** | https://github.com/ezsystems/ezpublish-kernel/pull/2958 |
| **Type**| feature
| **Target version** |`v3.0.0`
See https://github.com/ezsystems/ezpublish-kernel/pull/2958 for more details. Usage example:
```
{"SiblingCriterion": 54}
```
**TODO**:
> EZP-31415: Impl. input parser for Sibling criterion

- composer.json
- tests/bundle/Functional/ContentTest.php
> JIRA: https://jira.ez.no/browse/EZP-31501
> Passing build: https://travis-ci.org/github/ezsystems/ezplatform-rest/builds/665053371
Since we decided to remove `minimum-stability` and `prefer-stable` from `composer.json` it's now impossible to install the package because of unresolved depencencies. This PR `ezsystems/doctrine-dbal-schema` package required by ezpublish-kernel.
> EZP-31501: Added missing ezsystems/doctrine-dbal-schema package

- src/lib/Server/Input/Parser/Query.php
- tests/bundle/Functional/ContentTest.php
- tests/lib/Server/Input/Parser/FacetBuilder/FacetBuilderParserTest.php
- tests/lib/Server/Input/Parser/QueryParserTest.php
JIRA: [EZP-31183](https://jira.ez.no/browse/EZP-31183)
Using the `Criteria` element in REST input query (search view) payload has been deprecated since eZ Platform 1.6.
An example of deprecated usage:
``` xml
<ViewInput>
<identifier>testCreateView</identifier>
<Query>
<Criteria>
<ContentTypeIdentifierCriterion>folder</ContentTypeIdentifierCriterion>
</Criteria>
<limit>10</limit>
<offset>0</offset>
</Query>
</ViewInput> 
```
Instead of Criteria either Query or Filter should be used.
**TODO**:
> EZP-31183: Dropped support for Criteria element in REST search queries

- tests/bundle/Functional/RoleTest.php
| **JIRA issue**     | https://jira.ez.no/browse/EZP-31578
| **Target version** | 1.0, master
Build are currently failing on Travis: https://travis-ci.org/github/ezsystems/ezplatform-rest/branches
And that's because of incorrect codestyle. This PR fixes that.
**TODO**:
> [CS] Fixed CS

- src/lib/Server/Controller/Views.php
- src/lib/Server/Input/Parser/ViewInput.php
- src/lib/Server/Input/Parser/ViewInputOneDotOne.php
- src/lib/Server/Values/RestViewInput.php
| **JIRA issue**     | [EZP-31680](https://jira.ez.no/browse/EZP-31680)
| **Target version** | eZ Platform v3.0
This PR is a direct continuation of https://github.com/ezsystems/ezpublish-kernel/pull/3043
REST views will now utilize `languageCode` param in order to find `Content` in the chosen language.
Related `admin-ui` PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1407
Side note: Rest visitor is not able to receive any language info as it is created out of `Location` object - https://github.com/ezsystems/ezplatform-rest/blob/master/src/lib/Server/Output/ValueObjectVisitor/RestContent.php#L41 It would …
> EZP-31680: Provided `languageCode` param to REST Views

- .travis.yml
Failing build: https://travis-ci.org/github/ezsystems/ezplatform-rest/builds/714309764 (master, but this branch is also affected).
PHP_IMAGE_* variables have to be adjusted after ezsystems/ezplatform#588
> [Travis] Adjusted PHP_IMAGE_ variables to Docker changes

- src/lib/Server/Output/ValueObjectVisitor/RestExecutedView.php
| **JIRA issue**     | [EZP-31776](https://jira.ez.no/browse/EZP-31776)
| **Target version** | eZ Platform v3.1
When loading Location via REST main Location might not be accessible for the end-user due to permissions which results in Unauthorized Exception even though the user can have access to different Locations of this Relation.
This PR is a direct follow-up on the v2.5 PR: https://github.com/ezsystems/ezpublish-kernel/pull/3055
**TODO**:
> EZP-31776: Provided 'null' as Location in RestExecutedView if unavailable

- src/lib/Server/Input/Parser/LocationUpdate.php
- tests/lib/Server/Input/Parser/LocationUpdateTest.php
| **JIRA issue**     | [EZP-31039](https://jira.ez.no/browse/EZP-31039)
| **Target version** | v3.1
`updateLocation` API method doesn't require the existence of sort params in `LocationUpdateStruct` (it will use params already stored in the Location itself), we can remove them when parsing REST data.
Related `ezplatform-admin-ui` PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1643
Parent `ezpublish-kernel` PR: https://github.com/ezsystems/ezpublish-kernel/pull/3071
**TODO**:
> EZP-31039: Skip requirement of sort params when updating Location via REST

- src/bundle/Resources/config/input_parsers.yml
| **JIRA issue**     | [EZP-32107](https://jira.ez.no/browse/EZP-32107)
| **Requires** | https://github.com/ezsystems/ezplatform-kernel/pull/130
| **Type**| feature
| **Target version** | `v3.3.0`
Example request:
```http
POST http://localhost:8000/api/ezp/v2/views
Accept: application/json
Content-Type: application/vnd.ez.api.ViewInput+json; version=1.1
X-CSRF-Token: {{CSRF_TOKEN}}
{
"ViewInput": {
"identifier": "view_with_sort_score",
"ContentQuery": {
"limit": "10",
"offset": "0",
"Query": {
"FullTextCriterion": "Ibexa"
},
"SortClauses": {
"Score": "descending"
}
}
}
}
```
**TODO**:
> EZP-32107: Impl. visitor for Score sort clause

- src/lib/FieldTypeProcessor/ImageAssetFieldTypeProcessor.php
| **JIRA issue**     | [EZP-32128](https://jira.ez.no/browse/EZP-32128)
| **Target version** | `v3.2`
**TODO**:
> EZP-32128: Variations hrefs no longer generated for removed image asset relation

- src/bundle/Resources/config/services.yml
- src/lib/Server/Controller/SessionController.php
| **JIRA issue**     | [EZP-32215](https://jira.ez.no/browse/EZP-32215)
| **Target version** | eZ Platform `v3.3.0`
When installing the app with flex we are not able to override security.yaml file which breaks compiling the container. `ezpublish_rest.controller.session` has a dependency on `ezpublish_rest.session_authenticator` which isn't created unless `ezpublish_rest_session` is configured for a firewall.
I made the dependency optional. When you access affected endpoint it will throw an Exception explaining invalid security configuration. 
**TODO**:
> EZP-32215: Made `ezpublish_rest.session_authenticator` dependency optional

- src/bundle/DependencyInjection/Compiler/FieldTypeProcessorPass.php
- src/bundle/Resources/config/services.yml
- tests/bundle/DependencyInjection/Compiler/FieldTypeProcessorPassTest.php
| **JIRA issue**     | [EZP-32340](https://jira.ez.no/browse/EZP-32340)
| **Target version** | `3.2`+
Deprecated `ezpublish_rest.field_type_processor` in favour of `ezplatform.field_type.rest.processor`.
**TODO**:
> EZP-32340: Deprecated ezpublish_rest.field_type_processor in favour of ibexa.rest.field_type.processor

- src/bundle/Resources/config/services.yml
- src/lib/Input/Dispatcher.php
- src/lib/Input/ParsingDispatcher.php
| **JIRA issue**     | none
| **Target version** | v3.3
This PR fixes issues discovered when working on ez commerce rest.
* phpdoc fixes for wrong return types, more specific argument types
* services declaration injects more services than are declared in constructor (potential BC break here?)
Not included in PR, but available - `InputHandlerPass` can be removed and replaced with `!tagged_iterator` indexed by `format` tag attribute (would change / delay the exception).
> Fixed discrepancies between phpdoc / service config and actual declarations

- src/bundle/EventListener/CsrfListener.php
- src/bundle/Resources/config/routing.yml
- tests/bundle/EventListener/CsrfListenerTest.php
- tests/bundle/EventListener/EventListenerTest.php
| **JIRA issue**     | [IBX-833](https://jira.ez.no/browse/IBX-833)
| **Target version** | 3.3.7+
Allow to configure CSRF validation in REST endpoints using 
```yaml
csrf_protection: false
```
attribute in route definition.
Currently to achive the same efect `\EzSystems\EzPlatformRestBundle\EventListener\CsrfListener::isSessionRoute` needs to be overriden:
```php
class CsrfListener implements EventSubscriberInterface
protected function isSessionRoute($route)
{
return in_array(
$route,
['ezpublish_rest_createSession', 'ezpublish_rest_refreshSession', 'ezpublish_rest_deleteSession']
);
}
}
```
Example use cases:
* …
> IBX-833: As a Developer I want to configure CSRF validation in REST endpoints

- composer.json
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-984](https://issues.ibexa.co/browse/IBX-984)
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.3`+
| **BC breaks**                          | yes
The `hautelook/templated-uri-bundle` package disappeared from open source ecosystem without any explanation, so we had to fork it and use our own for instead.
> IBX-984: Replaced hautelook/templated-uri-bundle with Ibexa fork
