ezsystems/ezplatform-rest

.travis.yml, .travis/prepare_ezplatform.sh, composer.json, phpunit-integration-rest.xml
~DO NOT MERGE BEFORE REMOVING TMP COMMIT.~
Can be merged now :)
=> Added Travis config

.travis.yml, composer.json, tests/bundle/DependencyInjection/Compiler/OutputVisitorPassTest.php, tests/bundle/EventListener/ResponseListenerTest.php, tests/bundle/Functional/SearchViewTest.php, tests/bundle/Functional/SessionTest.php, tests/bundle/Functional/TestCase.php, tests/bundle/Routing/OptionsLoader/MapperTest.php, tests/bundle/Routing/OptionsLoader/RouteCollectionMapperTest.php, tests/lib/FieldTypeProcessor/BinaryInputProcessorTest.php, tests/lib/Input/FieldTypeParserTest.php, tests/lib/Output/Generator/FieldTypeHashGeneratorBaseTest.php, tests/lib/Server/Output/ValueObjectVisitor/BookmarkListTest.php, tests/lib/Server/Output/ValueObjectVisitor/CachedValueTest.php, tests/lib/Server/Output/ValueObjectVisitor/RestFieldDefinitionTest.php, tests/lib/Server/Output/ValueObjectVisitor/VersionInfoTest.php, tests/lib/Server/Output/ValueObjectVisitor/VersionTest.php, tests/lib/Server/Security/CsrfTokenManagerTest.php, tests/lib/Server/Security/RestLogoutHandlerTest.php, tests/lib/Server/Security/RestSessionBasedAuthenticatorTest.php
> JIRA: -
- Upgraded tests to PHPUnit 8
- Fixed env variables names in .travis.yml
- Added "kriswallsmith/buzz" to dev dependencies
- Changed matrix to run `phpunit-integration-rest.xml` directly from its package
=> Upgraded tests to PHPUnit 8 and fixed executing integration tests on Travis

src/bundle/Resources/config/routing.yml, src/lib/Server/Controller/Content.php
Merge up of following PR:
https://github.com/ezsystems/ezpublish-kernel/pull/2767
=> EZP-30382: Added content hide/reveal to REST API

.php_cs, composer.json
> JIRA: https://jira.ez.no/browse/EZP-31108
=> EZP-31108: Provided common PHP CS Fixer configuration for internal use

src/bundle/Resources/config/value_object_visitors.yml, src/lib/Server/Output/ValueObjectVisitor/RestContent.php, tests/lib/Server/Output/ValueObjectVisitor/RestContentTest.php
| **JIRA issue**     | [EZP-31125](https://jira.ez.no/browse/EZP-31125)
Mirrored https://github.com/ezsystems/ezpublish-kernel/pull/2885
**TODO**:
=> EZP-31125: Added TranslatedName to Content/ContentInfo in REST response

tests/lib/Input/FieldTypeParserTest.php, tests/lib/Server/Input/Parser/FieldDefinitionUpdateTest.php, tests/lib/Server/Output/ValueObjectVisitor/ContentFieldValidationExceptionTest.php
| **JIRA issue**     | -
| **Type**| maintenance  
| **Tests pass**     | ?
| **Doc needed**     |no
See https://travis-ci.org/ezsystems/ezplatform-rest/jobs/627617772?utm_medium=notification&utm_source=github_status 
**TODO**:
=> Fixed broken unit tests

tests/bundle/Functional/SearchViewTest.php
| **JIRA issue**     | A follow-up to [EZP-30806](https://jira.ez.no/browse/EZP-30806)
Refactored REST Functional SearchViewTest based on the changes from [`eZ/Bundle/EzPublishRestBundle/Tests/Functional/SearchViewTest.php`](https://github.com/ezsystems/ezpublish-kernel/blob/b433d9946a2f328091bb126f9e1a44e29bf5717d/eZ/Bundle/EzPublishRestBundle/Tests/Functional/SearchViewTest.php)
but excluding unsupported in eZ Platform 3.0 payload format:
``` json
"OR": [
{
"ContentTypeIdentifierCriterion": "folder"
},
{
"ContentTypeIdentifierCriterion": "article"
}
]
```
=> [Tests] Refactored REST SearchViewTest and provided more payloads

src/lib/Server/Output/ValueObjectVisitor/Version.php, tests/bundle/Functional/xsd/Version.xsd
| **JIRA issue**     | [EZP-30882](https://jira.ez.no/browse/EZP-30882)
| **Type**| feature
**TODO**:
=> EZP-30882: Exposed Thumbnail in REST Version

src/lib/Server/Controller/ContentType.php, src/lib/Server/Output/ValueObjectVisitor/ContentTypeList.php, tests/lib/Server/Input/Parser/ContentCreateTest.php, tests/lib/Server/Input/Parser/FieldDefinitionUpdateTest.php, tests/lib/Server/Input/Parser/UserCreateTest.php, tests/lib/Server/Input/Parser/UserGroupCreateTest.php, tests/lib/Server/Output/ValueObjectVisitor/ContentTypeListTest.php
| **JIRA issue**     | [EZP-31078](https://jira.ez.no/browse/EZP-31078)
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** |  `master`
| **BC breaks**      | yes
Adapted `ezplatform-rest` to changes introduced in https://github.com/ezsystems/ezpublish-kernel/pull/2839
**TODO**:
=> EZP-31078: Enhanced Content Type Value Object

src/lib/Server/Output/ValueObjectVisitor/Exception.php, tests/lib/Server/Output/ValueObjectVisitor/ExceptionTest.php
| **JIRA issue**     | [EZP-31298](https://jira.ez.no/browse/EZP-31298)
Migrated my bugfix from https://github.com/ezsystems/ezpublish-kernel/pull/2945
**TODO**:
=> EZP-31298: Made non verbose exception messages in REST responses

tests/bundle/Functional/SearchView/Criterion/IsUserBasedTest.php, tests/bundle/Functional/SearchView/Criterion/IsUserEnabledTest.php, tests/bundle/Functional/SearchView/Criterion/ObjectStateIdentifierTest.php, tests/bundle/Functional/SearchView/Criterion/SectionIdentifierTest.php, tests/bundle/Functional/SearchView/Criterion/SiblingTest.php, tests/bundle/Functional/SearchView/Criterion/UserEmailTest.php, tests/bundle/Functional/SearchView/Criterion/UserIdTest.php, tests/bundle/Functional/SearchView/Criterion/UserLoginTest.php, tests/bundle/Functional/SearchView/SearchCriterionTestCase.php
| **JIRA issue**     | [EZP-31415](https://jira.ez.no/browse/EZP-31415)
| **Target version** |`v3.0.0`
Follow up for https://github.com/ezsystems/ezplatform-rest/pull/40
**TODO**:
=> EZP-31415: Added functional tests for Sibling Criterion

tests/lib/Server/Output/ValueObjectVisitor/RestExecutedViewTest.php
| **JIRA issue**     |-
| **Target version** |  `v3.0.0`
Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2998
**TODO**:
=> Adjusted unit tests to recent changes

composer.json
| **JIRA issue**     | [EZP-31531](https://jira.ez.no/browse/EZP-31531)
| **BC breaks**      |no
=> EZP-31531: Used hautelook/templated-uri-bundle instead of our fork

src/bundle/Resources/config/services.yml, src/lib/Server/Service/ExpressionRouterRootResourceBuilder.php, tests/lib/Server/Output/ValueObjectVisitor/RootTest.php
| **JIRA issue**     | [EZP-30543](https://jira.ez.no/browse/EZP-30543)
| **BC breaks**      | yes/no
| **Tests pass**     | yes/no
**TODO**:
=> EZP-30543: Removed Dynamic Settings functionality from kernel

tests/bundle/Functional/SearchView/Criterion/UserEmailTest.php, tests/bundle/Functional/UserTest.php, tests/lib/Server/Input/Parser/UserCreateTest.php, tests/lib/Server/Input/Parser/UserUpdateTest.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | https://issues.ibexa.co/browse/EZEE-3453
| **Type**                                   |bug
| **Target eZ Platform version** | `v3.2`
| **BC breaks**                          |no
| **Doc needed**                       |no
This PR provides fixed tests after cleandata change. Related to: https://github.com/ezsystems/ezplatform-kernel/pull/162
**TODO**:
=> EZEE-3453: Fixed tests after cleandata change

src/bundle/DependencyInjection/Compiler/FieldTypeProcessorPass.php, tests/bundle/DependencyInjection/Compiler/FieldTypeProcessorPassTest.php
| **JIRA issue**     | [EZP-32340](https://jira.ez.no/browse/EZP-32340)
| **Target version** | e.g.: eZ Platform `v3.0.0`
Applied https://github.com/ezsystems/ezplatform-rest/pull/63#discussion_r578960026.
**TODO**:
=> EZP-32340: Fixed FieldTypeProcessorPass::{FIELD_TYPE_PROCESSOR_SERVICE_TAG,DEPRECATED_FIELD_TYPE_PROCESSOR_SERVICE_TAG} access modifier

src/lib/Server/Input/Parser/Criterion/DateMetadata.php, tests/lib/Server/Input/Parser/Criterion/DateMetadataTest.php
| **JIRA issue**     | [IBX-366](https://issues.ibexa.co/browse/IBX-366)
| **Type**| feature/improvement
| **Target version** | `v3.3`
Merge up from: https://github.com/ezsystems/ezpublish-kernel/pull/3100
**TODO**:
=> IBX-366: Implemented DateMetadataCriterion to REST API

tests/lib/FieldTypeProcessor/BinaryInputProcessorTest.php
| **Target version** | `master` - rebranding purpose
There is a minor syntax error issue in this file and it prevented lexer to parse it for rebranding purpose.
**TODO**:
=> Fixed test syntax error preventing lexer parsing the file

src/bundle/Resources/config/input_parsers.yml, src/lib/Server/Input/Parser/Aggregation/Location/LocationChildrenTermAggregationParser.php
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-704
| **Target version** | `v3.2`
Added input parsers for https://github.com/ezsystems/ezplatform-kernel/pull/215
=> IBX-704: Added input parser for LocationChildrenTermAggregation

src/lib/Server/Controller/Location.php
| **JIRA issue**     | -
| **Target version** | 3.3+
Fixed code style issues reporeted by CI: https://app.travis-ci.com/github/ezsystems/ezplatform-rest/jobs/541408733
**TODO**:
=> Fixed code style issues
